srms_new/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from student.controllers.dashboard_controller import index

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index, name='home'),
    path('students/', include('student.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

student/urls.py
from django.urls import path
from student.controllers.dashboard_controller import DashboardView,registerPage,find_result_view,PasswordChangeView,result
from student.controllers.result_controller import declare_result_view,result_update_view,result_delete_view,DeclareResultListView,validate_data,setup_update_view
from student.controllers.class_controller import StudentClassCreateView,StudentClassUpdateView,StudentClassDeleteView,StudentClassListView
from student.controllers.student_controller import StudentListView,StudentCreateView,StudentUpdateView,StudentDeleteView
from student.controllers.subject_controller import SubjectListView,SubjectCreateView,SubjectUpdateView,SubjectDeleteView
from student.controllers.com_subj_class_controller import SubjectCombinationListView,SubjectCombinationDeleteView,SubjectCombinationUpdateView,SubjectCombinationCreateView
from student.controllers.ID_controller import IDCreateView,IDDeleteView,IDListView,IDUpdateView
from student.controllers.calender_controller import calender_Holiday

urlpatterns = [
    path('',DashboardView.as_view(), name='dashboard'),
    path('register/',registerPage, name='register'),
    path('find-result/',find_result_view, name='find_result'),
    path('change-password/', PasswordChangeView.as_view(), name='change_password'),
    path('find-result/<int:pk>/result/',result, name='get_result'),
    path('declare/',declare_result_view, name='declare_result'),
    path('result/update/<int:pk>/', result_update_view, name='update_result'),
    path('result/delete/<int:pk>/', result_delete_view, name='delete_result'),
    path('result/list/', DeclareResultListView.as_view(), name='result_list'),
    path('declare/validate/', validate_data, name='validate_data'),
    path('declare/setup/', setup_update_view, name='setup'),
    path('class/create/', StudentClassCreateView.as_view(), name='create_class'),
    path('class/update/<int:pk>/', StudentClassUpdateView.as_view(), name='update_class'),
    path('class/delete/<int:pk>/', StudentClassDeleteView.as_view(), name='delete_class'),
    path('class/list/', StudentClassListView.as_view(), name='class_list'),
    path('student/', StudentListView.as_view(), name='student_list'),
    path('student/create/', StudentCreateView.as_view(), name='student_create'),
    path('student/update/<int:pk>', StudentUpdateView.as_view(), name='student_update'),
    path('student/delete/<int:pk>', StudentDeleteView.as_view(), name='student_delete'),
    path('subject/', SubjectListView.as_view(), name='subject_list'),
    path('subject/create/', SubjectCreateView.as_view(), name='create_subject'),
    path('subject/update/<int:pk>/', SubjectUpdateView.as_view(), name='update_subject'),
    path('subject/delete/<int:pk>/', SubjectDeleteView.as_view(), name='delete_subject'),
    path('combination/create/', SubjectCombinationCreateView.as_view(), name='create_subject_combination' ),
    path('combination/list/', SubjectCombinationListView.as_view(), name='subject_combination_list' ),
    path('combination/update/<int:pk>', SubjectCombinationUpdateView.as_view(), name='subject_combination_update' ),
    path('combination/delete/<int:pk>', SubjectCombinationDeleteView.as_view(), name='subject_combination_delete' ),
    path('student/id/', IDListView.as_view(), name='id_list'),
    path('student/id/create/', IDCreateView.as_view(), name='id_create'),
    path('student/id/update/<int:pk>',IDUpdateView.as_view(), name='id_update'),
    path('student/id/delete/<int:pk>', IDDeleteView.as_view(), name='id_delete'),
    path('calendar/', calender_Holiday, name='calendar'),
]

student/models.py
from django.db import models

# Create your models here.

student/models/Class.py
from django.db import models
from django.urls import reverse

class StudentClass(models.Model):
    class_name              =   models.CharField(max_length=100, help_text='Eg- IT 19, IT 20, MGT 20 etc')
    section                 =   models.CharField(max_length=10, help_text='Eg- 1, 2, 3 etc')
    creation_date           =   models.DateTimeField(auto_now=False, auto_now_add=True)

    def get_absolute_url(self):
        return reverse('class_list')

    def __str__(self):
        return "%s Section-%s"%(self.class_name, self.section)

student/models/Com_subj_class.py
from django.db import models
from django.urls import reverse
from student.models.Class import StudentClass
from student.models.subject import Subject

class SubjectCombination(models.Model):
    select_class = models.ForeignKey(StudentClass,on_delete=models.CASCADE)
    select_subject = models.ManyToManyField(Subject)

    def get_absolute_url(self):
        return reverse('subject_combination_list')

    def __str__(self):
        return '%s Section-%s'%(self.select_class.class_name, self.select_class.section)

student/models/ID.py
from django.db import models
from django.urls import reverse

class Student_ID(models.Model):
    student_num = models.CharField(max_length=5,help_text='00001,00002, etc.')

    def get_absolute_url(self):
        return reverse('id_create')

    def __str__(self):
        return self.student_num

student/controllers/ID_controller.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from student.models.ID import Student_ID
from student.forms import IDForm
from django.urls import reverse_lazy


class IDCreateView(LoginRequiredMixin, CreateView):
    model = Student_ID
    form_class = IDForm
    template_name='id/id_form.html'
    def get_context_data(self, **kwargs):
        context = super(IDCreateView, self).get_context_data(**kwargs)
        context['main_page_title'] = 'Student ID Creation'
        context['panel_name'] = 'Student ID'
        context['panel_title'] = 'Add Student ID'
        return context

class IDListView(LoginRequiredMixin, ListView):
    model = Student_ID
    template_name='id/id_list.html'
    field_list = [
        'Student id'
    ]
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_page_title'] = 'Manage Student ID'
        context['panel_name']   =   'Student ID'
        context['panel_title']  =   'View Student ID Info'
        context['field_list']   =   self.field_list
        return context

class IDUpdateView(LoginRequiredMixin,UpdateView):
    model = Student_ID
    template_name='id/id_form.html'
    form_class = IDForm
    success_url = reverse_lazy('id_list')

class IDDeleteView(LoginRequiredMixin, DeleteView):
    model = Student_ID
    template_name= 'id/id_delete.html'
    success_url = reverse_lazy('id_list')

    def get_context_data(self, **kwargs):
        context = super(IDDeleteView, self).get_context_data(**kwargs)
        context['main_page_title'] = 'Student ID Delete Confirmation'
        context['panel_name'] = 'Student ID'
        context['panel_title'] = 'Delete Student ID'
        return context

student/controllers/calender_controller.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
import requests

def calender_Holiday(request):
        endpoint = 'https://date.nager.at/api/v2/publicholidays/2021/ID'
        response = requests.get(endpoint)
        data = response.json()
        context = {
            'datas':data,
        }
        return render(request,'holiday_list/holiday_list.html',context=context)

student/controllers/class_controller.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from student.models.Class import StudentClass
from student.forms import StudentClassForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

class StudentClassCreateView(LoginRequiredMixin, CreateView):
    model = StudentClass
    form_class = StudentClassForm
    template_name = 'class/studentclass_form.html'
    def get_context_data(self, **kwargs):
        context = super(StudentClassCreateView, self).get_context_data(**kwargs)
        context['main_page_title'] = 'Add Student Class'
        context['panel_name'] = 'Classes'
        context['panel_title'] = 'Add Class'
        return context

class StudentClassListView(LoginRequiredMixin, ListView):
    model = StudentClass
    template_name='class/studentclass_list.html'
    field_list = [
        'Class Name', 'Section', 'Creation Date'
    ]
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_page_title'] = 'Manage Classes'
        context['panel_name']   =   'Classes'
        context['panel_title']  =   'View Classes Info'
        context['field_list']   =   self.field_list
        return context

class StudentClassUpdateView(LoginRequiredMixin, UpdateView):
    model = StudentClass
    form_class = StudentClassForm
    template_name = 'class/studentclass_form.html'
    success_url = reverse_lazy('class_list')

class StudentClassDeleteView(LoginRequiredMixin, DeleteView):
    model = StudentClass
    template_name = 'class/studentclass_delete.html'
    success_url = reverse_lazy('class_list')

    def get_context_data(self, **kwargs):
        context = super(StudentClassDeleteView, self).get_context_data(**kwargs)
        context['main_page_title'] = 'Class Delete Confirmation'
        context['panel_name'] = 'Classes'
        context['panel_title'] = 'Delete Class'
        return context

student/controllers/com_subj_class_controller.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from student.models.Com_subj_class import SubjectCombination
from student.forms import SubjectCombinationForm
from django.urls import reverse_lazy

class SubjectCombinationCreateView(LoginRequiredMixin, CreateView):
    model = SubjectCombination
    form_class = SubjectCombinationForm
    template_name = 'com_subj_class/subjectcombination_form.html'

    def get_context_data(self, **kwargs):
        context = super(SubjectCombinationCreateView, self).get_context_data(**kwargs)
        context['main_page_title'] = 'SubjectCombination Creation'
        context['panel_name'] = 'SubjectConbinations'
        context['panel_title'] = 'Create SubjectConbination'
        return context

class SubjectCombinationListView(LoginRequiredMixin, ListView):
    model = SubjectCombination
    template_name = 'com_subj_class/subjectcombination_list.html'
    field_list = [
        'Class', 'Section', 'Subject'
    ]
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_page_title'] = 'Manage SubjectCombinations'
        context['panel_name']   =   'SubjectCombinations'
        context['panel_title']  =   'View SubjectCombinations Info'
        context['field_list']   =   self.field_list
        return context

class SubjectCombinationUpdateView(LoginRequiredMixin, UpdateView):
    model = SubjectCombination
    template_name = 'com_subj_class/subjectcombination_form.html'
    form_class = SubjectCombinationForm
    success_url = reverse_lazy('subject_combination_list')

class SubjectCombinationDeleteView(LoginRequiredMixin, DeleteView):
    model = SubjectCombination
    template_name = 'com_subj_class/subjectcombination_delete.html'
    success_url = reverse_lazy('subject_combination_list')

    def get_context_data(self, **kwargs):
        context = super(SubjectCombinationDeleteView, self).get_context_data(**kwargs)
        context['main_page_title'] = 'SubjectCombination Delete Confirmation'
        context['panel_name'] = 'SubjectCombinations'
        context['panel_title'] = 'Delete SubjectCombination'
        return context

student/controllers/dashboard_controller.py
from xhtml2pdf import pisa
from django.template.loader import get_template
from django.http import HttpResponse
from io import BytesIO
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import authenticate, login
from django.views.generic import TemplateView, View
from django.contrib.auth.models import User
from student.models.result import DeclareResult
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.core import serializers
import json

from django.contrib import messages
from student.forms import CreateUserForm
from student.models.Class import StudentClass
from student.models.subject import Subject
from student.models.student import Student


def index(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        print("\nUser Name = ",username)
        print("Password = ",password)
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('dashboard')
        else:
            context = {'message':'Invalid User Name and Password'}
            return render(request, 'dashboard/index.html', context)
    return render(request, 'dashboard/index.html', {})

def registerPage(request):
    form = CreateUserForm()
    if request.method =='POST':
        email = request.POST['email']
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user= form.cleaned_data.get('username')
            template = render_to_string('dashboard/email.html',{'username':request.user.username})
            sent = render_to_string('dashboard/send.html')
            email = EmailMessage(
                'Account - E-Mail validation',
                template,
                settings.EMAIL_HOST_USER,
                [email],
            )
            email.fail_silently = False
            email.send()
            return HttpResponse(sent)
    context = {'form':form}
    return render(request, 'dashboard/register.html', context)



class DashboardView(LoginRequiredMixin,TemplateView):
    template_name = "dashboard/dashboard.html"

    
    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['cls'] = StudentClass.objects.count()
        context['results'] = DeclareResult.objects.count()
        context['students'] = Student.objects.count()
        context['subjects'] = Subject.objects.count()
        return context
    

def find_result_view(request):
    student_class = DeclareResult.objects.all()
    if request.method == "POST":
        data = request.POST
        # data = json.loads(form)
        roll = int(data['rollid'])
        pk = int(data['class'])
        clss = get_object_or_404(DeclareResult, pk=pk)
        if clss.select_student.student_roll == roll:
            data = {
                'pk': data['class']
            }
            return JsonResponse(data)
        else:
            pk = '0'
            data = {
                'pk': pk
            }
            return JsonResponse(data)
    return render(request, 'dashboard/find_result.html', {'class':student_class})

def result(request, pk):
    object = get_object_or_404(DeclareResult, pk=pk)
    lst = []
    marks = []
    for i in range(int(len(object.marks)/2)):
        lst.append(object.marks['subject_'+str(i)])
        lst.append(object.marks['subject_'+str(i)+'_mark'])
        marks.append(lst)
        lst = []
    return render(request, 'dashboard/result.html', {'object':object,'pk':pk, 'marks':marks})


class PasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    success_url = reverse_lazy('dashboard:dashboard')
    template_name = 'password_change_form.html'

    
    def get_context_data(self, **kwargs):
        context = super(PasswordChangeView, self).get_context_data(**kwargs)
        context['main_page_title'] = 'Admin Change Password'
        context['panel_title'] = 'Admin Change Password'
        return context


def renderPdf(template, content={}):
    t = get_template(template)
    send_data = t.render(content)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(send_data.encode("ISO-8859-1")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    else:
        return None

class pdf(View):
    def get(self, request, id):
        try:
            query = get_object_or_404(DeclareResult, id=id)
        except:
            Http404('Content Not Found')
        marks = []
        lst = []
        for i in range(int(len(query.marks)/2)):
            lst.append(query.marks['subject_'+str(i)])
            lst.append(query.marks['subject_'+str(i)+'_mark'])
            marks.append(lst)
            lst = []
        article_pdf = renderPdf('dashboard/result.html', {'object': query, 'marks':marks})
        return HttpResponse(article_pdf, content_type='application/pdf')

student/views.py
from django.shortcuts import render

# Create your views here.

student/templates/result/declareresult_form.html
{% extends 'base.html' %}
{% block top_js %}
    
{% endblock top_js %}
    
{% block main_page_title %}
{{ main_page_title }}
{% endblock main_page_title %}

{% block breadcumb %}
<li><a href="{% url 'result_list' %}">{{ panel_name }}</a></li>
<li class="active">{{ panel_title }}</li>
{% endblock breadcumb %}

{% block panel %}
<div class="col-md-12">
    <div class="panel">
        <div class="panel-heading">
            <div class="panel-title">
                <h5>{{ panel_title }}</h5>
            </div>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" data-url="{{ request.build_absolute_uri | safe }}">{% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_input }}" class="col-sm-2 control-label">{{ field.label_tag }}</label>
                        <div class="col-sm-10">
                            {{ field }}
                        </div>
                    </div>
                {% endfor %}
                <div class="ajax_load">
                    <div class="form-group">
                        <label for="success" class="col-sm-2 control-label">Subjects:</label>
                        <div class="col-sm-10" id="add_field">
                            
                        </div>
                    </div>
                    <input type="submit" value="Save" name="save" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock panel %}


{% block javascript_code %}
<script>
    $(document).ready(function(){
        // Handle Field Change
        $('.ajax_load').hide()
        $("select#id_select_class").change(function () {
            var $selectedClass = $(this).children("option:selected").text();
            var $thisUrl = '/results/declare/validate/'

            $.ajax({
                method  :   'GET',
                url: $thisUrl,
                data: {
                    'selectedClass':$selectedClass
                },
                dataType: 'json',
                success: function(json){
                    $('.ajax_load').show()
                    var myObj = JSON.parse(json.subjects)
                    $('#add_field').empty()
                    var subjectName = myObj[0].fields.subject_name
                    for (let i = 0; i < myObj.length; i++) {
                        subjectName = myObj[i].fields.subject_name

                        code = '<div class="form-group"><div class="col-sm-2"><label for="" class="control-label">'+ subjectName +'</label></div ><div class="col-sm-6"><input type="hidden" name="subject_'+i+'" value="' + subjectName +'"><input type="number" name="subject_' + i +'_mark" class="form-control" placeholder="Enter Mark For ' + subjectName +'"></div></div>';

                        $('#add_field').append(code)                    
                    }
                    
                },
                error: handleFormError,
            })
        });
        
        // Handel Form Submition
        var $myForm = $('.form-horizontal')
        $myForm.submit(function (event) {
            event.preventDefault()
            var $formData = $(this).serialize()
            var $thisURL = $myForm.attr('data-url') || window.location.href // or set your own url
            $.ajax({
                method: "POST",
                url: $thisURL,
                data: $formData,
                success: function(){
                    console.log("Successfully Send data")
                    $myForm[0].reset()
                    window.location.reload()
                },
                error: handleFormError,
            })
        
        })

        function handleFormError(jqXHR, textStatus, errorThrown) {
            console.log(jqXHR)
            console.log(textStatus)
            console.log(errorThrown)
        }
    })
</script>

{% endblock javascript_code %}

student/templates/result/declareresult_list.html
{% extends 'base.html' %}

{% block main_page_title %}
{{ main_page_title }}
{% endblock main_page_title %}

{% block breadcumb %}
<li><a href="{% url 'result_list' %}">{{ panel_name }}</a></li>
<li class="active">{{ panel_title }}</li>
{% endblock breadcumb %}

{% block panel_title %}
{{ panel_title }}
{% endblock panel_title %}

{% block panel %}
{% include 'includes/manage_panel_top.html' %}
{% for object in object_list %}
<tr role="row" class="odd">
    <td class="">{{ object.id }}</td>
    <td class="">{{ object.select_student.student_name }}</td>
    <td class="">{{ object.select_student.student_roll }}</td>
    <td class="">{{ object.select_student.student_class }}</td>
    <td class="">{{ object.select_student.student_reg }}</td>
    <td class="">{{ object.marks.subject_0_mark }} | {{ object.marks.subject_1_mark }} | {{ object.marks.subject_2_mark }}</td>
    <td>
        <a href="{% url 'update_result' object.id %}" class="btn btn-primary"><i class="fa fa-edit" title="Edit Record"></i>
        </a>
        <a href="{% url 'delete_result' object.id %}" class="btn btn-danger"><i class="fa fa-trash" title="Delete Record"></i>
        </a>

    </td>
</tr>
{% endfor %}
{% include 'includes/manage_panel_bottom.html' %}
{% endblock panel %}


{% block javascript_code %}
<script>
</script>
{% endblock javascript_code %}

student/templates/result/result_delete.html
{% extends 'base.html' %}
{% block top_js %}

{% endblock top_js %}

{% block main_page_title %}
{{ main_page_title }}
{% endblock main_page_title %}

{% block breadcumb %}
<li><a href="{% url 'result_list' %}">{{ panel_name }}</a></li>
<li class="active">{{ panel_title }}</li>
{% endblock breadcumb %}

{% block panel %}
<div class="col-md-12">
    <div class="panel">
        <div class="panel-heading">
            <div class="panel-title">
                <h5>{{ panel_title }}</h5>
            </div>
        </div>
        <div class="panel-body">
            <form class="form-horizontal text-center" method="post" data-url="{{ request.build_absolute_uri | safe }}">{% csrf_token %}
                <h2>Are you sure you want to delete result of "{{ object.select_student }}"?</h2>
                <input type="submit" value="Confirm" class="btn btn-danger">
                <button class="btn btn-primary"><a href="{% url 'result_list' %}">Cancel</a></button>
            </form>
        </div>
    </div>
</div>
{% endblock panel %}

student/templates/result/update_form.html
{% extends 'base.html' %}
{% block top_js %}

{% endblock top_js %}

{% block main_page_title %}
{{ main_page_title }}
{% endblock main_page_title %}

{% block breadcumb %}
<li><a href="{% url 'result_list' %}">{{ panel_name }}</a></li>
<li class="active">{{ panel_title }}</li>
{% endblock breadcumb %}

{% block panel %}
<div class="col-md-12">
    <div class="panel">
        <div class="panel-heading">
            <div class="panel-title">
                <h5>{{ panel_title }}</h5>
            </div>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" data-url="{{ request.build_absolute_uri | safe }}">{%csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_input }}" class="col-sm-2 control-label">{{ field.label_tag }}</label>
                    <div class="col-sm-10">
                        {{ field }}
                    </div>
                </div>
                {% endfor %}
                <p id="pk" style="display:none">{{ pk }}</p>
                <div class="ajax_load">
                    <div class="form-group">
                        <label for="success" class="col-sm-2 control-label">Subjects:</label>
                        <div class="col-sm-10" id="add_field">

                        </div>
                    </div>
                    <input type="submit" value="Save" name="save" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock panel %}


{% block javascript_code %}
<script>
$(document).ready(function(){
    console.log("Document Ready")
    var pk_value = $('#pk').text()
    // Sending Primary Key and Setup Update Form
    $.ajax({
        method  :   'GET',
        url     :   '/results/declare/setup/',
        dataType:   'json',
        data    :   {
            'pk_value'   :   pk_value
        },
        success :   function(data){
            dt = data.dt
            size = Object.keys(dt).length/2
            for (let i = 0; i < size; i++) {
                html = '<div class="form-group"><div class="col-sm-2"><label for="" class="control-label">' + dt['subject_'+i] + '</label></div ><div class="col-sm-6"><input type="hidden" name="subject_' + i + '" value="' + dt['subject_' + i] + '"><input type="number" name="subject_' + i + '_mark" class="form-control" value="'+dt['subject_'+i+'_mark']+'"></div></div>';
                $('#add_field').append(html)
            }
        
        },
        error   :   function(error){
            alert("Ooops!! error"+error)
        }
    })

    // Sending Form Data for update form
    var $myForm = $('.form-horizontal')
    $myForm.submit(function (event) {
        var $formData = $(this).serialize()
        $.ajax({
            method: "POST",
            url: '/results/update/'+pk_value+'/',
            data: $formData,
            success: function () {
                $myForm[0].reset()
                 window.location('http://127.0.0.1:8000/results/update/' + pk_value + '/')
            },
            error: handleFormError,
        })

    })

    function handleFormError(jqXHR, textStatus, errorThrown) {
        console.log(jqXHR)
        console.log(textStatus)
        console.log(errorThrown)
    }
})

</script>


{% endblock javascript_code %}